default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: angle_analyzer_development

test:
  <<: *default
  database: angle_analyzer_test

production:
  <<: *default
  database: angle_analyzer_production
  username: angle_analyzer
  password: <%= ENV['ANGLE_ANALYZER_DATABASE_PASSWORD'] %>
